theme = "base16_transparent"

[editor]
auto-save = true
completion-replace = true
cursorcolumn = false
cursorline = true
line-number = "relative"
mouse = false
true-color = true
color-modes = true
rulers = [79]
bufferline = "multiple"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "spinner",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "none"
nbsp = "all"
tab = "none"
newline = "none"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊"
skip-levels = 0

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40

[keys.normal]
# esc is remapped to capslock locally
esc = ["collapse_selection", "keep_primary_selection"]
C-v = "vsplit"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
"C-," = "goto_previous_buffer"
"C-." = "goto_next_buffer"
"K" = "insert_newline"
# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before"
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before"
]

[keys.normal.g]
q = ":bc"
Q = ":bc!"

# Remove vscode "training wheels"
# Comment this to enable arrow navigation in insert mode
[keys.insert]
j = { k = "normal_mode" }
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
# VSCode-like auto-completeion (pretty much all IDEs do it on C-space)
"C-space" = "completion"

# Config Mode
[keys.normal."C-backspace"]
r = ":config-reload"
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"
