[[language]]
name = "toml"
auto-format = true
# https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml
formatter = { command = "prettier", args = ["--parser", "toml"] }

[[language]]
name = "markdown"
auto-format = true
# https://github.com/executablebooks/mdformat
formatter = { command = "mdformat", args = ["-"] }
