# https://github.com/nametake/golangci-lint-langserver
# [language-server.golangci-lint]
# command = "golangci-lint-langserver"
# config = { command = [
#   "golangci-lint",
#   "run",
#   "--enable-all",
#   "--disable",
#   "lll",
#   "--out-format",
#   "json",
#   "--issues-exit-code=1"
# ] }
# --------
[[language]]
name = "toml"
auto-format = true
# https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml
formatter = { command = "prettier", args = ["--parser", "toml"] }

[[language]]
name = "markdown"
auto-format = true
# https://github.com/executablebooks/mdformat
formatter = { command = "mdformat", args = ["-"] }
# ---
# [[language]]
# name = "go"
# language-servers = ["gopls", "golangci-lint"]
